version: '2'
services:
  agent:
    image: datadog/docker-dd-agent:latest
    environment:
      - API_KEY
      - DD_APM_ENABLED=true
      - SD_BACKEND=docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc:ro
      - /cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - 8125:8125/udp
      - 8126:8126/tcp
    privileged: true
    labels:
      - convox.agent=true
      - convox.balancer=false
